---
title: "cohort-assembly-&-harmonization_occams-best2"
author: "Shawn Zamani"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r packages}
require(tidyverse)
require(reshape2)
# library(RColorBrewer)
# require(circlize)
# require(grid) 
# require(gridExtra) 
# require(cowplot)
```


Common variables:

 - Phenotype
 - Age
 - gender
 - ethnicity
 - BMI
 - smk_ever_smoked
 - taken_nsaids
 - acid_suppressant
 - duration_since_heartburn_start
 
 # Read data
 
```{r}
best2 <- read_csv('data/processed/chapter.2_regression_best2-cohort_cleaned-data_20230208.csv')
occams <- read_csv('data/processed/chapter.2_regression_occams-cohort_cleaned-data_20230119.csv')
# occams <- read_csv('data/processed/chapter.2_regression_occams-cohort_cleaned-filtered_cohort-excludes_bo_surveillance_20230213.csv')

```

# Harmonize

```{r}
occams_cohort <- occams %>% 
  mutate(
        gender = case_when(gender == "female" ~ "F", gender == "male" ~ "M", TRUE ~ gender),
        smk_ever_smoked = case_when(smk_ever_smoked == "ever" ~ "Y", smk_ever_smoked == "never" ~ "N", TRUE ~ smk_ever_smoked),
        duration_since_heartburn_start = case_when(duration_since_heartburn_start == "never" ~ "Never", TRUE ~ duration_since_heartburn_start),
  )

best2_cohort <- best2
```

# Combine cohorts and deduplicate

4,717 cases total 
```{r}
occams_best2_all_cohort <- bind_rows(best2_cohort, occams_cohort) %>%
  mutate(taken_nsaids = case_when(
    ID %in% c(
      'BEST2/CAM/0134',
      'BEST2/CAM/0141',
      'BEST2/CAM/0819',
      'BEST2/NTY/0009'
    ) ~ 'Y',
    TRUE ~ taken_nsaids
  )) %>% distinct()
```
# Save dataset
```{r}
# write_csv(occams_best2_all_cohort, 'data/processed/chapter.2_occams_best2_all_cohort.csv')
# write_csv(occams_best2_all_cohort, 'data/processed/chapter.2_occams_best2_all_cohort_20221215.csv')
# write_csv(occams_best2_all_cohort, 'data/processed/chapter.2_occams_best2_all_cohort_20230111.csv')
# write_csv(occams_best2_all_cohort, 'data/processed/chapter.2_occams_best2_all_cohort_20230119.csv')
# write_csv(occams_best2_all_cohort, 'data/processed/chapter.2_occams_best2_all_cohort_filtered_cohort-exclude_bo_surveillance_20230213.csv')
```
