---
title: "02_OAC-MutSigs"
author: "Shawn Zamani"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# packages ----------------------------------------------------------------
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(rstatix)
# library(GGally)
# library(ggridges) 
# library(patchwork)
# library(ggbreak)
# library(gtsummary)
```

# read and prepare data
```{r}
OAC_710_cohort <-
  vroom::vroom('data/original/wgs/case_spec_dna_occams_oac_normal.710.csv', col_names = FALSE) %>%
  transmute(
    ID = str_replace(X1, 'OC/', 'OCCAMS/'),
    spec_oac = X2,
    dna_oac = X3,
    dna_normal = X4
  ) %>%
  select(-spec_oac) %>%
  rename(abnormal_DNA_ID = dna_oac,
         normal_DNA_ID = dna_normal) %>%
  unite(col = DNA_ID, abnormal_DNA_ID, normal_DNA_ID, remove = FALSE, sep = '_vs_')
```

```{r}
# process mut_sig files ----------------------------------------------------------------
# data from Maria Secrier November 2021

load('data/original/wgs/710_signatures_maria/sigs.allSamples.normalised.202101127_cosmicref13sig_S3S8.RData')
OAC_MutSig_allSamples <- sigs.allSamples %>% rownames_to_column(var = 'DNA_ID')

load('data/original/wgs/710_signatures_maria/sigs.allSamples.absolute.202101127_cosmicref13sig_S3S8.RData')
OAC_MutSig_allSamples_absolute <- sigs.allSamples.absolute %>% rownames_to_column(var = 'DNA_ID')

# find which IDs  samples and if all of my samples are found in the data from Maria
# 
# 
occams_wgs_thesis_cohort <-
  inner_join(
    OAC_710_cohort,
      read_csv('data/processed/wgs_processed/occams_thesis_wgs_cohort_20230402.csv') %>%
  mutate(
    BMI_Class_f = case_when(
      BMI_Class_f == "normal" ~ "0_normal",
      BMI_Class_f == "underweight" ~ "0_normal",
      BMI_Class_f == "overweight" ~ "2_overweight",
      BMI_Class_f == "obese" ~ "3_obese"
    )
  ) %>%
  mutate(Smoker_Ever = case_when(
    Smoker_Ever == 'never' ~ 'N',
    Smoker_Ever == 'ever' ~ 'Y',
  )) %>%
  mutate(across(.cols = c(10:15), ~ as.character(.x))) %>%
  mutate(across(.cols = c(10:15), ~ replace_na(.x, "z_unknown"))) %>%
  mutate(across(.cols = c(28:34), ~ as.character(.x))) %>%
  mutate(across(.cols = c(28:34), ~ replace_na(.x, "z_unknown"))) %>%
  mutate(across(.cols = c(37:46), ~ as.character(.x))) %>%
  mutate(across(.cols = c(37:46), ~ replace_na(.x, "z_unknown"))),
  by = 'ID'
  )

OAC_MPE_MutSig_allSamples <-
inner_join(OAC_MutSig_allSamples, occams_wgs_thesis_cohort, "DNA_ID") %>% 
    mutate(# combines the "low contribution" sigs into other category but keep the summed components
    SBS_Other =
      SBS3 +
      SBS8 +
      SBS28 +
      SBS30 +
      SBS35 +
      SBS41 +
      SBS44) %>%
  relocate(
    # reorders the variables
    .after = DNA_ID,
    SBS1,
    SBS2,
    SBS3,
    SBS5,
    SBS8,
    SBS17a,
    SBS17b,
    SBS18,
    SBS28,
    SBS30,
    SBS35,
    SBS40,
    SBS41,
    SBS44,
    SBS_Other
  )


OAC_MPE_MutSig_allSamples_absolute <-
  inner_join(OAC_MutSig_allSamples_absolute, occams_wgs_thesis_cohort, "DNA_ID") %>%
  mutate(# combines the "low contribution" sigs into other category but keep the summed components
    SBS_Other =
      SBS3 +
      SBS8 +
      SBS28 +
      SBS30 +
      SBS35 +
      SBS41 +
      SBS44) %>%
  relocate(
    # reorders the variables
    .after = DNA_ID,
    SBS1,
    SBS2,
    SBS3,
    SBS5,
    SBS8,
    SBS17a,
    SBS17b,
    SBS18,
    SBS28,
    SBS30,
    SBS35,
    SBS40,
    SBS41,
    SBS44,
    SBS_Other
  )




write_csv(OAC_MPE_MutSig_allSamples_absolute, 'data/processed/paper/oac_mut-sigs-absolute_20240507.csv')

```

# signture presence
```{r}

# New facet label names for phenotype variable
UK_phenotype_labs <- c(
  "BE/IM EAC" = "BE+ve EAC",
  "Non-BE/IM EAC" = "BE-ve EAC",
  "Unknown BE/IM EAC" = "BE(?) EAC"
)
OAC_MPE_MutSig_allSamples_absolute %>%
  # select(-c(SBS3,
  #           SBS8,
  #           SBS28,
  #           SBS30,
  #           SBS35,
  #           SBS41,
  #           SBS44)) %>%
  select(-SBS_Other) %>% 
  select(abnormal_DNA_ID, Phenotype, contains('SBS')) %>%
  reshape2::melt(variable = 'signature', value.name = 'mutations') %>% 
  filter(mutations>0) %>% 
  mutate(sig_present = 'TRUE') %>% 
  group_by(Phenotype, signature, sig_present) %>% 
  count(name = 'n_sig_present') %>% 
  mutate(prop_sig_present0 = 
           case_when(Phenotype=='BE/IM EAC' ~  n_sig_present / 252,
           Phenotype=='Non-BE/IM EAC' ~  n_sig_present / 183,
           Phenotype=='Unknown BE/IM EAC' ~  n_sig_present / 275)) %>% 
  mutate(prop_sig_present = as.double(round(prop_sig_present0, digits = 3)*100)) %>% 
  # filter(signature=='SBS17b') 
  ggplot(aes(Phenotype, prop_sig_present)) +
  geom_col() +
  facet_wrap(vars(signature), nrow = 7) +
  scale_x_discrete(labels = UK_phenotype_labs) +
  xlab('Phenotype')+
  ylab('% of cases with signature') +
  # scale_y_continuous(limits = c(0,81)) +
  theme_bw() +
      theme(legend.position = 'none',
        # axis.ticks.y.left = element_blank(),
        # axis.text.y.left = element_blank(),
        # axis.title.x = element_blank(), 
        # axis.title.y = element_blank(), 
        axis.text.x = element_text(size = 12, angle = 35, vjust = 1, hjust=1),
        axis.text.y = element_text(size = 12)
        ) 



```


# TMB v sigs

```{r}
OAC_MPE_MutSig_allSamples_absolute

oac_all_cohort_tmb <- read_csv('data/processed/wgs_processed/oac_all_cohort_tmb_20230404.csv')

oac_sigs_tmb_epi <- inner_join(oac_all_cohort_tmb, OAC_MPE_MutSig_allSamples, "ID")

oac_sigs_tmb_epi %>% 
    filter(total_count < 270000) %>%
    # select(-c(SBS3,
    #         SBS8,
    #         SBS28,
    #         SBS30,
    #         SBS35,
    #         SBS41,
    #         SBS44)) %>%
  # select(ID, Phenotype, total_count, contains('SBS')) %>%
  # reshape2::melt(variable = 'signature', value.name = 'mutations') %>% 
  ggplot(aes(total_count, SBS17a)) + 
  geom_point() +
  coord_cartesian(xlim = c(0, 2.75*10^5)) 
# 3.5*3.0 Portrait
oac_sigs_tmb_epi %>%
  filter(total_count < 270000) %>%
  ggscatter(
    x = 'total_count',
    y = 'SBS17b',
    color = 'Phenotype',
    add = "reg.line",
    size = 1,
    conf.int = TRUE,
    show.legend = FALSE,
    palette =  c("#e41a1c", "#377eb8", "#CC0099")
  ) +
  # stat_cor(method = "pearson", show.legend = FALSE, label.y = c(300000)) +
  # facet_grid(cols = vars(Phenotype)) 
  stat_cor(aes(color = Phenotype), method = "pearson", show.legend = FALSE) +
  scale_color_manual(
    breaks = c("BE/IM EAC", "Non-BE/IM EAC", "Unknown BE/IM EAC"),
    labels = c("BO+ve OAC", "BO-ve OAC", "BO(?) OAC"),
    values = c("#e41a1c", "#377eb8", "#CC0099")
  ) +
  ylab('SBS17b proportion') +
  xlab('Total mutations') +
  theme_bw() +
  theme(
    legend.position = c(.85, 1),
    legend.text = element_text(size = 5),
    legend.title = element_text(size = 5),
    legend.key.size = unit(.25, 'cm'),
    legend.title.align = 0.5,
    legend.direction = "vertical") 

```

# Desnity plot of all signatures

```{r}
MPE_MutSig_allSamples_melt_ggpdata <- OAC_MPE_MutSig_allSamples %>%
  select(abnormal_DNA_ID, Phenotype, contains('SBS')) %>%
  # select(-SBS_Other) %>% 
  # mutate(# combines the "low contribution" sigs into other category but keep the summed components
  #   SBS_Other =
  #     # SBS2 +
  #     SBS3 +
  #     SBS8 +
  #     SBS28 +
  #     SBS30 +
  #     SBS35 +
  #     SBS41 +
  #     SBS44) %>%
reshape2::melt(variable = 'signature', value.name = 'proportion') %>% 
    mutate(signature = factor(signature,
                            rev(
                              c(
                                'SBS17a',
                                'SBS17b',
                                'SBS1',
                                'SBS2',
                                'SBS5',
                                'SBS13',
                                'SBS18',
                                'SBS40',
                                
                                'SBS3',
                                'SBS8',
                                'SBS28',
                                'SBS30',
                                'SBS35',
                                'SBS41',
                                'SBS44',
                                'SBS_Other'
                              )
                            )))

# New facet label names for phenotype variable
UK_phenotype_labs <- c(
  "BE/IM EAC" = "BO+ve OAC",
  "Non-BE/IM EAC" = "BO-ve OAC",
  "Unknown BE/IM EAC" = "BO(?) OAC"
)

MPE_MutSig_allSamples_melt_ggpdata %>%
  ggplot(aes(x = proportion, y = signature)) +
  geom_density_ridges(
    aes(fill = signature),
    quantile_lines = TRUE,
    quantiles = 2,
    scale = 1.5,
    # alpha = .50,
    vline_size = .5,
    vline_color = 'red',
    rel_min_height = 0.01,
    position = position_points_jitter(width = 0.05, height = 0)
  ) +
  facet_grid(cols = vars(Phenotype),
             labeller = as_labeller(UK_phenotype_labs)) +
  # ylab('Signature') +
  xlab('Signature proportion') +
  scale_fill_manual(values = rev(
    c(
      "#E41A1C",
      "#377EB8",
      "#4DAF4A",
      "#984EA3",
      "#FF7F00",
      "#FFFF33",
      "#A65628",
      "#CCCCCC",
      "#CCCCCC",
      "#CCCCCC",
      "#CCCCCC",
      "#CCCCCC",
      "#CCCCCC",
      "#CCCCCC",
      "#818181"
    )
  )) +
  theme_bw() +
  theme(legend.position = 'NONE',
        legend.title.align = 0.5,
        text = element_text(size = 14),
        # axis.title.x = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank()) +
) + coord_cartesian(xlim = c(0, 0.5))
```


# Pie chart

```{r}
OAC_MPE_MutSig_allSamples_absolute_piechart <-
  OAC_MPE_MutSig_allSamples_absolute %>%
  select(-c(
            SBS3,
            SBS8,
            SBS28,
            SBS30,
            SBS35,
            SBS41,
            SBS44)) %>%
  select(abnormal_DNA_ID,
         Phenotype,
         contains('SBS')) %>%
  reshape2::melt(variable = 'signature', value.name = 'signature_muts') %>%
  group_by(Phenotype, signature) %>%
  summarise(total_signature_mutations = sum(signature_muts)) %>% 
  ungroup() %>% 
  mutate(perc_signature_mutations = 
           case_when(
             Phenotype == 'BE/IM EAC' ~ total_signature_mutations/7106519,
             Phenotype == 'Non-BE/IM EAC' ~ total_signature_mutations/5075652,
             Phenotype == 'Unknown BE/IM EAC' ~ total_signature_mutations/7493917,
           )) %>% 
  # mutate(labels1 = round(perc_signature_mutations, digits = 4)) %>% 
  mutate(text_y = cumsum(perc_signature_mutations) - perc_signature_mutations/2) %>% 
  mutate(labels = scales::percent(perc_signature_mutations, accuracy = 0.1)) %>% 
  mutate(signature = factor(
    signature,
    c(
      'SBS17a',
      'SBS17b',
      'SBS1',
      'SBS2',
      'SBS5',
      'SBS18',
      'SBS40',
      'SBS_Other'
    )
  ))


OAC_MPE_MutSig_allSamples_absolute_piechart %>%
  ggplot(aes(x = "",  y = perc_signature_mutations, fill = signature)) +
  geom_col(position = 'fill') +
  geom_label_repel(aes(label = labels),
             # position = position_stack(vjust = .3),
             # nudge_x = .05,
             # nudge_y = .5,
             # label.padding = unit(.35, units = 'cm'),
             size = 2,
             show.legend = FALSE) +
  coord_polar(theta = "y", direction = -1) +
  facet_grid(cols = vars(Phenotype),labeller = as_labeller(UK_phenotype_labs)) +
  scale_fill_manual(
    values = c(
      "#E41A1C",
      "#377EB8",
      "#4DAF4A",
      "#984EA3",
      "#FF7F00",
      "#FFFF33",
      "#A65628",
      "#818181"
    )
  ) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'top',
    panel.grid =element_blank(),
    legend.text = element_text(size = 12), 
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    # strip.background = element_blank(),
    # strip.text.x = element_blank(),
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()) +
    guides(fill = guide_legend(nrow = 2, byrow=TRUE)) 

# 4.5*6.5
```

# Waterfall plot

```{r}

OAC_MPE_MutSig_allSamples_absolute %>%
  filter(DNA_ID!='LP6008460-DNA_B04_vs_LP6008340-DNA_F02') %>%
  filter(DNA_ID!='LP6008269-DNA_D09_vs_LP6008268-DNA_D09') %>% 
  select(-c(SBS3,
            SBS8,
            SBS28,
            SBS30,
            SBS35,
            SBS41,
            SBS44)) %>%
  select(abnormal_DNA_ID,
         Phenotype,
         contains('SBS')) %>%
  reshape2::melt(variable = 'signature', value.name = 'signature_muts') %>%
  mutate(signature = factor(
    signature,
    c(
      'SBS17a',
      'SBS17b',
      'SBS1',
      'SBS2',
      'SBS5',
      'SBS18',
      'SBS40',
      'SBS_Other'
    )
  )) %>%
  ggplot(aes(x = reorder(abnormal_DNA_ID,-signature_muts), y = signature_muts)) +
  geom_col(aes(fill = signature), position = 'stack', width = 3) +
  facet_grid(cols = vars(Phenotype), scales = 'free',labeller = as_labeller(UK_phenotype_labs)) +
  scale_fill_manual(
    values = c(
      "#E41A1C",
               "#377EB8",
               "#4DAF4A",
               "#984EA3",
               "#FF7F00",
               "#FFFF33",
               "#A65628",
               "#818181"
    )
  ) +
  ylab('Total mutations') +
  theme_bw() +
  theme(
    legend.position = 'right',
    text = element_text(size = 12),
    # axis.text.y.left = element_text(size = 12),
    # axis.text.y.left = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y.right = element_blank(),
    # axis.title.y.left = element_text(size = 12),
    # strip.background = element_blank(),
    # strip.text.x = element_blank(),
    strip.text.y = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank())+
    guides(fill = guide_legend(title="Signature", ncol = 1, byrow=TRUE)) +
  coord_cartesian(ylim = c(0, 2.75*10^5)) 
  # scale_y_break(c(100000, 175000), scale = 0.15)

```

# Boxplots


```{r}
my_comparisons <- list( c("BE/IM EAC", "Non-BE/IM EAC"), c("BE/IM EAC", "Unknown BE/IM EAC"), c("Non-BE/IM EAC", "Unknown BE/IM EAC") )

wilcox <- OAC_MPE_MutSig_allSamples %>%
  filter(Phenotype!='Unknown BE/IM EAC')

wilcox.test(wilcox$SBS17a~wilcox$Phenotype)

# read old data because the new data does not add up
# OAC_MPE_MutSig_allSamples_old <- readr::read_csv('../../Somatic/somatic-analysis/data/processed_data/OAC_MPE_MutSig_allSamples_20220604.csv') %>%   mutate(
#     Phenotype = case_when(
#       RP.BarrettsAdjacentToTumour.c == "yes" ~ "BE/IM EAC",
#       RP.BarrettsAdjacentToTumour.c == "no" ~ "Non-BE/IM EAC",
#       is.na(RP.BarrettsAdjacentToTumour.c) ~ "Unknown BE/IM EAC"
#     )
#   )



# top_row <-
bottom_row <-
  OAC_MPE_MutSig_allSamples %>%
  select(-c(SBS3,
            SBS8,
            SBS28,
            SBS30,
            SBS35,
            SBS41,
            SBS44)) %>%
  select(Phenotype, contains('SBS')) %>% 
  reshape2::melt(variable = 'signature', value.name = 'proportion') %>%
  mutate(signature = factor(
    signature,
    c(
      'SBS17a',
      'SBS17b',
      'SBS1',
      'SBS2',
      'SBS5',
      'SBS18',
      'SBS40',
      'SBS_Other'
    )
  )) %>% 
  # filter(signature %in% c('SBS17a', 'SBS17b', 'SBS1', 'SBS2')) %>%
  filter(signature %in% c('SBS5', 'SBS18', 'SBS40', 'SBS_Other')) %>%
  ggplot(aes(x = Phenotype, y = proportion), labeller = as_labeller(UK_phenotype_labs)) +
  ggbeeswarm::geom_beeswarm(aes(color = ), size = .5) +
  geom_boxplot(aes(), alpha = .75)+
  # geom_violin(aes(), alpha = .75, draw_quantiles = c(0.5))+
  facet_wrap(vars(signature), nrow = 1, scales = 'free') +
  ggpubr::stat_compare_means(
    # method = 'kruskal.test',
    # method = 'wilcox',
    # paired = FALSE,
    # label.x = .7, 
    # vjust = 0.8,
    # label.y.npc = 0.4, 
    step.increase = .05,
    tip.length = 0,
    comparisons = my_comparisons, 
    label = "p.format",
    hide.ns = T,
    size = 2
  ) +
  theme_bw() +
  scale_x_discrete(labels = UK_phenotype_labs) +
  ylab('Signature proportion') +
  theme(
    text = element_text(size = 9),
    legend.position = 'none',
    # axis.text.x = element_blank(),
    axis.text.x.bottom = element_text(size = 9, angle = 15, vjust = 1, hjust=1),
    strip.text.x = element_text(margin = margin(0,0,0,0, "cm")),
    axis.title.x = element_blank()
    # axis.title.y = element_blank(),
    ) 
# 7*4.25 Landscape
library(patchwork)
top_row/bottom_row

OAC_MPE_MutSig_allSamples %>%
  group_by(Phenotype) %>% 
  summarise(median_sig_prop = median(SBS5),
            inter_q_range = quantile(SBS5))

# pvalues <- c(0.93, .28, .28, .0052, .37, .00046, .11, .68, .049)
# p.adjust(pvalues,method="BH")
# p val correction
# stat.test <- OAC_MPE_MutSig_allSamples_old %>%
  # select(-c(SBS3,
  #           SBS8,
  #           SBS28,
  #           SBS30,
  #           SBS35,
  #           SBS41,
  #           SBS44)) %>%
  # select(Phenotype, contains('SBS')) %>% 
  # reshape2::melt(variable = 'signature', value.name = 'proportion') %>%
  # mutate(signature = factor(
  #   signature,
  #   c(
  #     'SBS17a',
  #     'SBS17b',
  #     'SBS1',
  #     'SBS2',
  #     'SBS5',
  #     'SBS18',
  #     'SBS40',
  #     'SBS_Other'
  #   )
  # )) %>% 
  # group_by(signature) %>%
  # wilcox_test(proportion ~ Phenotype) %>%
  # adjust_pvalue(method = "BH") %>%
  # add_significance() %>% 
  # add_xy_position(x = "Phenotype") %>% 
  # mutate(p.adj = round(p.adj, digits = 3))

```


# Age

```{r}

```


# reflux

```{r}
OAC_MPE_MutSig_allSamples %>% 
  ggplot(aes(heartburn_inferred_bin, SBS17b))+
  facet_grid(cols = vars(Phenotype)) +
  geom_boxplot()

OAC_MPE_MutSig_allSamples %>% 
  ggplot(aes(Phenotype, SBS17b))+
  facet_grid(cols = vars(heartburn_inferred_bin)) +
  geom_boxplot()

OAC_MPE_MutSig_allSamples %>% 
  filter(Phenotype!='Unknown BE/IM EAC') %>% 
  group_by(heartburn_inferred_bin) %>% 
  wilcox_test(SBS17b~heartburn_inferred_bin)
```

# Sex

# Smoking

# Heartburn

# TMB

# Stage

```{r}
OAC_MPE_MutSig_allSamples %>%
  select(-c(SBS3,
            SBS8,
            SBS28,
            SBS30,
            SBS35,
            SBS41,
            SBS44)) %>%
  select(Phenotype, pTNM_f, contains('SBS')) %>% 
  reshape2::melt(variable = 'signature', value.name = 'proportion') %>%
  mutate(signature = factor(
    signature,
    c(
      'SBS17a',
      'SBS17b',
      'SBS1',
      'SBS2',
      'SBS5',
      'SBS18',
      'SBS40',
      'SBS_Other'
    )
  )) %>% 
  ggplot(aes(x = pTNM_f, y = proportion), labeller = as_labeller(UK_phenotype_labs)) +
  ggbeeswarm::geom_beeswarm(aes(color = ), size = .5) +
  geom_boxplot(aes(), alpha = .75)+
  # geom_violin(aes(), alpha = .75, draw_quantiles = c(0.5))+
  facet_grid(rows=vars(signature),scales = 'free') +
  # ggpubr::stat_compare_means(
    # method = 'kruskal.test',
    # method = 'wilcox',
    # paired = FALSE,
    # label.x = .8,
    # comparisons = my_comparisons, 
    # label = "p.format",
    # size = 3
  # ) +
  theme_bw() +
  scale_x_discrete(labels = UK_phenotype_labs) +
  ylab('Signature proportion') +
  theme(
    text = element_text(size = 12),
    legend.position = 'none',
    # axis.text.x = element_text(size = 12),
    axis.text.x = element_text(size = 9, angle = 25, vjust = 1, hjust=1),
    axis.title.x = element_blank()
    # axis.title.y = element_blank(),
    ) 

OAC_MPE_MutSig_allSamples %>% 
        mutate(pTNM_f = case_when(
    pTNM_f %in% c("I", "II") ~ "I/II",
    pTNM_f %in% c("III", "IV") ~ "III/IV",
    TRUE ~ pTNM_f
    )) %>% 
  ggplot(aes(x = pTNM_f, y = SBS17a), labeller = as_labeller(UK_phenotype_labs)) +
  geom_boxplot(aes(), alpha = .75) +
  stat_compare_means()

```


# Risk factor correlations

```{r}
library(broom)

glm_data <- OAC_MPE_MutSig_allSamples_absolute %>%
  # filter(Phenotype != 'Unknown BE/IM EAC') %>%
  select(-c(SBS3,
            SBS8,
            SBS28,
            SBS30,
            SBS35,
            SBS41,
            SBS44)) %>%
  mutate(
    SBS17a = log10(SBS17a + 1),
    SBS17b = log10(SBS17b + 1),
    SBS1 = log10(SBS1 + 1),
    SBS2 = log10(SBS2 + 1),
    SBS5 = log10(SBS5 + 1),
    SBS18 = log10(SBS18 + 1),
    SBS40 = log10(SBS40 + 1),
    SBS_Other = log10(SBS_Other + 1)
  ) %>%
  mutate(pTNM_f = case_when(
    pTNM_f %in% c("I", "II") ~ "I/II",
    pTNM_f %in% c("III", "IV") ~ "III/IV",
    TRUE ~ pTNM_f
  )) 


correlation_data <- glm_data %>%
  select(
    abnormal_DNA_ID,
    Phenotype,
    contains('SBS'),
    DI.ageAtDiagnosis,
    DI.PatientGender,
    BMI_n,
    Smoker_Ever,
    TAKEN_NSAIDS,
    heartburn_inferred_bin,
    EX.UnitsPerWeekInTotal,
    pTNM_f
  ) %>%
  reshape2::melt(
    id.vars = c(
      'abnormal_DNA_ID',
       'Phenotype',
      'DI.ageAtDiagnosis',
      'DI.PatientGender',
      'BMI_n',
      'Smoker_Ever',
      'TAKEN_NSAIDS',
      'heartburn_inferred_bin',
      'EX.UnitsPerWeekInTotal',
      'pTNM_f'
    )
  ) 


# library(purrr)
### All OAC
lm_output_all_oac <- correlation_data %>%
  nest_by(variable) %>%
  mutate(fit_age = list(lm(value ~ DI.ageAtDiagnosis, data = data)),
         fit_sex = list(lm(value ~ DI.PatientGender, data = data)),
         fit_bmi = list(lm(value ~ BMI_n, data = data)),
         fit_smk = list(lm(value ~ Smoker_Ever, data = data)),
         fit_nsa = list(lm(value ~ TAKEN_NSAIDS, data = data)),
         fit_hxb = list(lm(value ~ heartburn_inferred_bin, data = data)),
         fit_alc = list(lm(value ~ EX.UnitsPerWeekInTotal, data = data)),
         fit_tnm = list(lm(value ~ pTNM_f, data = data)))
         
coef_matrix_all_oac <- bind_rows(
lm_output_all_oac %>% summarize(tidy(fit_age)) %>% as_tibble(),
lm_output_all_oac %>% summarize(tidy(fit_sex)) %>% as_tibble(),
lm_output_all_oac %>% summarize(tidy(fit_bmi)) %>% as_tibble(),
lm_output_all_oac %>% summarize(tidy(fit_smk)) %>% as_tibble(),
lm_output_all_oac %>% summarize(tidy(fit_nsa)) %>% as_tibble(),
lm_output_all_oac %>% summarize(tidy(fit_hxb)) %>% as_tibble(),
lm_output_all_oac %>% summarize(tidy(fit_alc)) %>% as_tibble(),
lm_output_all_oac %>% summarize(tidy(fit_tnm)) %>% as_tibble()
)
### BO+ OAC
lm_output_bo_pos_oac <- correlation_data %>%
  filter(Phenotype == 'BE/IM EAC') %>% 
  nest_by(variable) %>%
  mutate(fit_age = list(lm(value ~ DI.ageAtDiagnosis, data = data)),
         fit_sex = list(lm(value ~ DI.PatientGender, data = data)),
         fit_bmi = list(lm(value ~ BMI_n, data = data)),
         fit_smk = list(lm(value ~ Smoker_Ever, data = data)),
         fit_nsa = list(lm(value ~ TAKEN_NSAIDS, data = data)),
         fit_hxb = list(lm(value ~ heartburn_inferred_bin, data = data)),
         fit_alc = list(lm(value ~ EX.UnitsPerWeekInTotal, data = data)),
         fit_tnm = list(lm(value ~ pTNM_f, data = data)))
         
coef_matrix_bo_pos_oac <- bind_rows(
lm_output_bo_pos_oac %>% summarize(tidy(fit_age)) %>% as_tibble(),
lm_output_bo_pos_oac %>% summarize(tidy(fit_sex)) %>% as_tibble(),
lm_output_bo_pos_oac %>% summarize(tidy(fit_bmi)) %>% as_tibble(),
lm_output_bo_pos_oac %>% summarize(tidy(fit_smk)) %>% as_tibble(),
lm_output_bo_pos_oac %>% summarize(tidy(fit_nsa)) %>% as_tibble(),
lm_output_bo_pos_oac %>% summarize(tidy(fit_hxb)) %>% as_tibble(),
lm_output_bo_pos_oac %>% summarize(tidy(fit_alc)) %>% as_tibble(),
lm_output_bo_pos_oac %>% summarize(tidy(fit_tnm)) %>% as_tibble()
)

### BO- OAC
lm_output_bo_neg_oac <- correlation_data %>%
  filter(Phenotype == 'Non-BE/IM EAC') %>% 
  nest_by(variable) %>%
  mutate(fit_age = list(lm(value ~ DI.ageAtDiagnosis, data = data)),
         fit_sex = list(lm(value ~ DI.PatientGender, data = data)),
         fit_bmi = list(lm(value ~ BMI_n, data = data)),
         fit_smk = list(lm(value ~ Smoker_Ever, data = data)),
         fit_nsa = list(lm(value ~ TAKEN_NSAIDS, data = data)),
         fit_hxb = list(lm(value ~ heartburn_inferred_bin, data = data)),
         fit_alc = list(lm(value ~ EX.UnitsPerWeekInTotal, data = data)),
         fit_tnm = list(lm(value ~ pTNM_f, data = data)))
         
coef_matrix_bo_neg_oac <- bind_rows(
lm_output_bo_neg_oac %>% summarize(tidy(fit_age)) %>% as_tibble(),
lm_output_bo_neg_oac %>% summarize(tidy(fit_sex)) %>% as_tibble(),
lm_output_bo_neg_oac %>% summarize(tidy(fit_bmi)) %>% as_tibble(),
lm_output_bo_neg_oac %>% summarize(tidy(fit_smk)) %>% as_tibble(),
lm_output_bo_neg_oac %>% summarize(tidy(fit_nsa)) %>% as_tibble(),
lm_output_bo_neg_oac %>% summarize(tidy(fit_hxb)) %>% as_tibble(),
lm_output_bo_neg_oac %>% summarize(tidy(fit_alc)) %>% as_tibble(),
lm_output_bo_neg_oac %>% summarize(tidy(fit_tnm)) %>% as_tibble()
)

### BO(?) OAC
lm_output_bo_unk_oac <- correlation_data %>%
  filter(Phenotype == 'Unknown BE/IM EAC') %>% 
  nest_by(variable) %>%
  mutate(fit_age = list(lm(value ~ DI.ageAtDiagnosis, data = data)),
         fit_sex = list(lm(value ~ DI.PatientGender, data = data)),
         fit_bmi = list(lm(value ~ BMI_n, data = data)),
         fit_smk = list(lm(value ~ Smoker_Ever, data = data)),
         fit_nsa = list(lm(value ~ TAKEN_NSAIDS, data = data)),
         fit_hxb = list(lm(value ~ heartburn_inferred_bin, data = data)),
         fit_alc = list(lm(value ~ EX.UnitsPerWeekInTotal, data = data)),
         fit_tnm = list(lm(value ~ pTNM_f, data = data)))
         
coef_matrix_bo_unk_oac <- bind_rows(
lm_output_bo_unk_oac %>% summarize(tidy(fit_age)) %>% as_tibble(),
lm_output_bo_unk_oac %>% summarize(tidy(fit_sex)) %>% as_tibble(),
lm_output_bo_unk_oac %>% summarize(tidy(fit_bmi)) %>% as_tibble(),
lm_output_bo_unk_oac %>% summarize(tidy(fit_smk)) %>% as_tibble(),
lm_output_bo_unk_oac %>% summarize(tidy(fit_nsa)) %>% as_tibble(),
lm_output_bo_unk_oac %>% summarize(tidy(fit_hxb)) %>% as_tibble(),
lm_output_bo_unk_oac %>% summarize(tidy(fit_alc)) %>% as_tibble(),
lm_output_bo_unk_oac %>% summarize(tidy(fit_tnm)) %>% as_tibble()
)

lm_matrix_labels <- rev(c(
  'Age at diagnosis \n (years)',
  'Male gender \n (reference: female)',
  'Body mass index \n (5 kg/m^2)',
  'Cigarette smoking \n (reference: never-smoker)',
  'Aspirin/NSAID use \n (reference: never-user)',
  'Presence of heartburn symptoms \n (reference: never)',
  'Alcohol use \n (standard units/week)',
  'TNM III/IV \n (reference: I/II)'
                      ))
```


## All OAC
```{r}

# landscape W 4.5* L 5.5
coef_matrix_all_oac %>%
  filter(term != '(Intercept)') %>%
  filter(!grepl("z_unknown", term)) %>%
  select(-c(std.error, statistic)) %>%
  mutate(coef_if_sig = ifelse(p.value < .05, exp(estimate) - 1, NA)) %>%
  mutate(BH_pval = p.adjust(p.value, 'BH')) %>%
  mutate(labels = scales::percent(coef_if_sig, accuracy = 0.1)) %>%
  mutate(labels = ifelse(is.na(labels), '', labels)) %>%
  mutate(labels = ifelse(term == 'EX.UnitsPerWeekInTotal', '', labels)) %>%
  mutate(estimate_trans = round((exp(estimate)-1) * 100, 2)) %>% 
  mutate(term = factor(term, rev(
    c(
      'DI.ageAtDiagnosis',
      'DI.PatientGendermale',
      'BMI_n',
      'Smoker_EverY',
      'TAKEN_NSAIDSY',
      'heartburn_inferred_binY',
      'EX.UnitsPerWeekInTotal',
      'pTNM_fIII/IV'
    )
  ), ordered = TRUE)) %>% 
  ggplot(aes(variable, term, fill = estimate_trans)) +    # Create default ggplot2 heatmap
  geom_tile(show.legend = TRUE) +
  geom_text(aes(label = labels), size = 3) +
  scale_y_discrete(labels = lm_matrix_labels, position = 'left')+
  scale_fill_gradient2(mid = "#FBFEF9", low = "#0C6291", high = "#A63446", 
                       name = 'Change in mutation frequency') +
  theme_bw() +
    theme(legend.position = 'top',
        axis.ticks.y.left = element_blank(),
        # axis.text.y.left = element_blank(),
        axis.title.x = element_blank(), 
        axis.title.y = element_blank(), 
        axis.text.x = element_text(size = 12, angle = 35, vjust = 1, hjust=1),
        axis.text.y = element_text(size = 12)
        ) 
  coord_fixed(ratio = 1.75) 


lm_matrix_labels <- rev(c(
  'Age at diagnosis \n (years)',
  'Male gender \n (reference: female)',
  'Body mass index \n (5 kg/m^2)',
  'Cigarette smoking \n (reference: never-smoker)',
  'Aspirin/NSAID use \n (reference: never-user)',
  'Presence of heartburn symptoms \n (reference: never)',
  'Alcohol use \n (standard units/week)',
  'TNM III/IV \n (reference: I/II)'
                      ))
```

## BO+ve OAC
```{r}

# landscape W 4.5* L 5.5
coef_matrix_bo_pos_oac %>%
  filter(term != '(Intercept)') %>%
  filter(!grepl("z_unknown", term)) %>%
  select(-c(std.error, statistic)) %>%
  mutate(coef_if_sig = ifelse(p.value < .05, exp(estimate) - 1, NA)) %>%
  mutate(labels = scales::percent(coef_if_sig, accuracy = 0.1)) %>%
  mutate(labels = ifelse(is.na(labels), '', labels)) %>%
  mutate(labels = ifelse(term == 'EX.UnitsPerWeekInTotal', '', labels)) %>%
  mutate(estimate_trans = round((exp(estimate)-1) * 100, 2)) %>% 
  mutate(term = factor(term, rev(
    c(
      'DI.ageAtDiagnosis',
      'DI.PatientGendermale',
      'BMI_n',
      'Smoker_EverY',
      'TAKEN_NSAIDSY',
      'heartburn_inferred_binY',
      'EX.UnitsPerWeekInTotal',
      'pTNM_fIII/IV'
    )
  ), ordered = TRUE)) %>% 
  ggplot(aes(variable, term, fill = estimate_trans)) +    # Create default ggplot2 heatmap
  geom_tile(show.legend = TRUE) +
  geom_text(aes(label = labels), size = 3) +
  scale_y_discrete(labels = lm_matrix_labels, position = 'left')+
  scale_fill_gradient2(mid = "#FBFEF9", low = "#0C6291", high = "#A63446",                        name = 'Change in mutation frequency') +
  ggtitle("BO+ve OAC")+
  theme_bw() +
    theme(legend.position = 'none',
        axis.ticks.y.left = element_blank(),
        # axis.text.y.left = element_blank(),
        axis.title.x = element_blank(), 
        axis.title.y = element_blank(), 
        axis.text.x = element_text(size = 10, angle = 35, vjust = 1, hjust=1),
        axis.text.y = element_text(size = 10)
        ) 
  coord_fixed(ratio = 1.75) 


lm_matrix_labels <- rev(c(
  'Age at diagnosis \n (years)',
  'Male gender \n (reference: female)',
  'Body mass index \n (5 kg/m^2)',
  'Cigarette smoking \n (reference: never-smoker)',
  'Aspirin/NSAID use \n (reference: never-user)',
  'Presence of heartburn symptoms \n (reference: never)',
  'Alcohol use \n (standard units/week)',
  'TNM III/IV \n (reference: I/II)'
                      ))
```

## BO-ve OAC
```{r}

# landscape W 4.5* L 5.5
coef_matrix_bo_neg_oac %>%
  filter(term != '(Intercept)') %>%
  filter(!grepl("z_unknown", term)) %>%
  select(-c(std.error, statistic)) %>%
  mutate(coef_if_sig = ifelse(p.value < .05, exp(estimate) - 1, NA)) %>%
  mutate(labels = scales::percent(coef_if_sig, accuracy = 0.1)) %>%
  mutate(labels = ifelse(is.na(labels), '', labels)) %>%
  mutate(labels = ifelse(term == 'EX.UnitsPerWeekInTotal', '', labels)) %>%
  mutate(estimate_trans = round((exp(estimate)-1) * 100, 2)) %>% 
  mutate(term = factor(term, rev(
    c(
      'DI.ageAtDiagnosis',
      'DI.PatientGendermale',
      'BMI_n',
      'Smoker_EverY',
      'TAKEN_NSAIDSY',
      'heartburn_inferred_binY',
      'EX.UnitsPerWeekInTotal',
      'pTNM_fIII/IV'
    )
  ), ordered = TRUE)) %>% 
  ggplot(aes(variable, term, fill = estimate_trans)) +    # Create default ggplot2 heatmap
  geom_tile(show.legend = TRUE) +
  geom_text(aes(label = labels), size = 3) +
  scale_y_discrete(labels = lm_matrix_labels, position = 'left')+
  scale_fill_gradient2(mid = "#FBFEF9", low = "#0C6291", high = "#A63446") +
  ggtitle("BO-ve OAC")+
  theme_bw() +
    theme(legend.position = 'none',
        axis.ticks.y.left = element_blank(),
        # axis.text.y.left = element_blank(),
        axis.title.x = element_blank(), 
        axis.title.y = element_blank(), 
        axis.text.x = element_text(size = 10, angle = 35, vjust = 1, hjust=1),
        axis.text.y = element_text(size = 10)
        ) 
  coord_fixed(ratio = 1.75) 


lm_matrix_labels <- rev(c(
  'Age at diagnosis \n (years)',
  'Male gender \n (reference: female)',
  'Body mass index \n (5 kg/m^2)',
  'Cigarette smoking \n (reference: never-smoker)',
  'Aspirin/NSAID use \n (reference: never-user)',
  'Presence of heartburn symptoms \n (reference: never)',
  'Alcohol use \n (standard units/week)',
  'TNM III/IV \n (reference: I/II)'
                      ))
```

## BO(?) OAC
```{r}

# landscape W 4.5* L 5.5
coef_matrix_bo_unk_oac %>%
  filter(term != '(Intercept)') %>%
  filter(!grepl("z_unknown", term)) %>%
  select(-c(std.error, statistic)) %>%
  mutate(coef_if_sig = ifelse(p.value < .05, exp(estimate) - 1, NA)) %>%
  mutate(labels = scales::percent(coef_if_sig, accuracy = 0.1)) %>%
  mutate(labels = ifelse(is.na(labels), '', labels)) %>%
  mutate(labels = ifelse(term == 'EX.UnitsPerWeekInTotal', '', labels)) %>%
  mutate(estimate_trans = round((exp(estimate)-1) * 100, 2)) %>% 
  mutate(term = factor(term, rev(
    c(
      'DI.ageAtDiagnosis',
      'DI.PatientGendermale',
      'BMI_n',
      'Smoker_EverY',
      'TAKEN_NSAIDSY',
      'heartburn_inferred_binY',
      'EX.UnitsPerWeekInTotal',
      'pTNM_fIII/IV'
    )
  ), ordered = TRUE)) %>% 
  ggplot(aes(variable, term, fill = estimate_trans)) +    # Create default ggplot2 heatmap
  geom_tile(show.legend = TRUE) +
  geom_text(aes(label = labels), size = 3) +
  scale_y_discrete(labels = lm_matrix_labels, position = 'left')+
  scale_fill_gradient2(mid = "#FBFEF9", low = "#0C6291", high = "#A63446") +
  ggtitle("BO(?) OAC")+
  theme_bw() +
    theme(legend.position = 'none',
        axis.ticks.y.left = element_blank(),
        # axis.text.y.left = element_blank(),
        axis.title.x = element_blank(), 
        axis.title.y = element_blank(), 
        axis.text.x = element_text(size = 10, angle = 35, vjust = 1, hjust=1),
        axis.text.y = element_text(size = 10)
        ) 
  coord_fixed(ratio = 1.75) 



```


