---
title: "05_OAC-ecdna"
author: "Shawn Zamani"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# packages ----------------------------------------------------------------
library(tidyverse)
library(ggplot2)
```


# read data

```{r}
load('data/original/wgs/710_ecdna/ecDNA-710_surival-analysis.RData') # Alvin's data
any_events <- any.events %>% 
  mutate(PatientId = str_trim(PatientId, side = 'both')) %>% 
  mutate(ID = str_replace_all(PatientId, 'OC/', 'OCCAMS/')) %>% 
  relocate(.before = Sample, ID) %>% 
  mutate()

occams_wgs_thesis_cohort <- read_csv('data/processed/wgs_processed/occams_thesis_wgs_cohort_20230402.csv')

occams_710_wgs_thesis_cohort <-
  vroom::vroom('data/original/wgs/case_spec_dna_occams_oac_normal.710.csv',
               col_names = FALSE) %>%
  transmute(
    ID = str_replace(X1, 'OC/', 'OCCAMS/'),
    spec_oac = X2,
    dna_oac = X3,
    dna_normal = X4
  ) %>%
  select(-spec_oac) %>%
  rename(abnormal_DNA_ID = dna_oac,
         normal_DNA_ID = dna_normal) %>%
  unite(
    col = DNA_ID,
    abnormal_DNA_ID,
    normal_DNA_ID,
    remove = FALSE,
    sep = '_vs_'
  ) %>%
  inner_join(.,
             occams_wgs_thesis_cohort,
             'ID')

ecdna_status <- inner_join(any_events, occams_710_wgs_thesis_cohort %>% select(ID, Phenotype), "ID")

write_csv(ecdna_status, 'data/processed/paper/ecDNA_status_20240507.csv')

```

## Any events

```{r}

UK_phenotype_labs <- c(
  "BE/IM EAC" = "BE+ve EAC",
  "Non-BE/IM EAC" = "BE-ve EAC",
  "Unknown BE/IM EAC" = "BE(?) EAC"
)


ecdna_data <- ecdna_status %>% 
  select(
    Phenotype, 
    ecDNA,
    # BFB,
    # Amplicon
    # Linear
    ) %>%
  reshape2::melt(variable.name='event',value.name = 'present') %>% 
  filter(present==1) %>% 
  group_by(Phenotype, event, present) %>% 
  count(name = 'n_mutated') %>% 
  mutate(prop_mutated0 =
           case_when(Phenotype=='BE/IM EAC' ~  n_mutated / 252,
           Phenotype=='Non-BE/IM EAC' ~  n_mutated / 183,
           Phenotype=='Unknown BE/IM EAC' ~  n_mutated / 275))

ecdna_status %>% 
  select(
    Phenotype, 
    # ecDNA,
    BFB,
    # Amplicon
    # Linear
    ) %>%
  reshape2::melt(variable.name='event',value.name = 'present') %>% 
  filter(present==1) %>% 
  group_by(Phenotype, event, present) %>% 
  count(name = 'n_mutated') %>% 
  mutate(prop_mutated0 =
           case_when(Phenotype=='BE/IM EAC' ~  n_mutated / 252,
           Phenotype=='Non-BE/IM EAC' ~  n_mutated / 183,
           Phenotype=='Unknown BE/IM EAC' ~  n_mutated / 275)) %>%
  mutate(prop_mutated = as.double(round(prop_mutated0, digits = 3)*100)) %>% 
  ggplot(aes(Phenotype, prop_mutated)) +
  geom_col(width = .75) +
  # facet_wrap(vars(event), nrow = 1) +
  scale_x_discrete(labels = UK_phenotype_labs) +
  xlab('Phenotype')+
  # ylab('% of tumours with ecDNA')+
  ylab('% of tumours with BFB events')+
  # ggpubr::stat_compare_means() +
  # scale_y_continuous(limits = c(0,81)) +
  theme_bw() +
      theme(legend.position = 'none',
        # axis.ticks.y.left = element_blank(),
        # axis.text.y.left = element_blank(),
        # axis.title.x = element_blank(), 
        # axis.title.y = element_blank(), 
        axis.text.x = element_text(size = 12, angle = 0),
        axis.text.y = element_text(size = 12)
        ) 


  
```

