---
title: "multiple-imputation"
author: "Shawn Zamani"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# mice
```{r}
library(mice)
library(tidyverse)
library(finalfit)
# Ruben's rules 
```

# raw data
```{r}
occams_best2_all_cohort_for_imputation <-
  read_csv('data/processed/chapter.2_occams_best2_all_cohort_20230119.csv') %>%
  mutate(Phenotype = factor(Phenotype, c("BE/IM EAC", "Non-BE/IM EAC"), ordered = TRUE)) %>% 
  select(
    -c(
      ID,
      age,
      gender,
      ethnicity,
      bmi,
      RP.SiewertClassification,
      acid_suppressant,
      duration_since_heartburn_start,
      pTStage_four_f
    )
  ) %>%
  mutate(
    bmi_group = case_when(
      bmi_group == "normal" ~ "0_normal",
      bmi_group == "underweight" ~ "0_normal",
      bmi_group == "overweight" ~ "2_overweight",
      bmi_group == "obese" ~ "3_obese"
    )
  ) %>%
  mutate(
    age_group = factor(
      age_group,
      c(
        '< 50 years old',
        '50 - 59 years old',
        '60 - 69 years old',
        '70+ years old'
      )
    ),
    # gender = factor(gender, c('F', 'M')),
    bmi_group = factor(bmi_group, c('0_normal' , '2_overweight' , '3_obese')),
    smk_ever_smoked = factor(smk_ever_smoked, c("N", "Y")),
    taken_nsaids = factor(taken_nsaids, c("N", "Y")),
    heartburn_inferred_bin = factor(heartburn_inferred_bin, c("N", "Y")),
    pTNM_f = factor(pTNM_f, c("I", "II", "III", "IV"))
  )

```

# inspect data

```{r}
md.pattern(occams_best2_all_cohort_for_imputation)
visdat::vis_miss(occams_best2_all_cohort_for_imputation %>% filter(Phenotype!='Barretts') %>% filter(Phenotype!='Control') %>% filter(Phenotype!='Unknown BE/IM EAC'), cluster = TRUE)
```

# impute

```{r}
BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_MI_data <-
  mice(
    occams_best2_all_cohort_for_imputation,
    m = 5,
    maxit = 2,
    printFlag = TRUE,
  )


```


# imputation diagnostics

```{r}

densityplot(BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_MI_data)
stripplot(BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_MI_data, pch = 20, cex = 1.2)
stripplot(BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_MI_data$data$smk_ever_smoked)


densityplot(BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_MI_data, ~ Phenotype)

```

# load model

```{r}
dependent <- "Phenotype"
independent <-
  c(
    "age_group",
    # "gender",
    'bmi_group',
    'smk_ever_smoked',
    'taken_nsaids',
    'heartburn_inferred_bin',
    'pTNM_f'
  )



```


# run model

```{r}
BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model <- BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_MI_data %>%
  with(glm(formula(ff_formula(
    dependent, independent
  )), family = "binomial"))


BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_pooled <- BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model %>% pool()

BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_pooled %>% fit2df(estimate_name = "OR (Multivar using MI)", exp = TRUE) %>% kableExtra::kable(caption = 'BE_IM_EAC_vs_Non_BE_IM_EAC') %>% kableExtra::kable_styling(full_width = FALSE)


 BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_data %>% or_plot(dependent, independent, glmfit = BE_IM_EAC_vs_Non_BE_IM_EAC_logit_model_pooled)
```

